# Generated by Django 5.2.5 on 2026-10-01 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_options_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.CharField(default='hi', max_length=255),
            preserve_default=False,
        ),
    ]
